add xdg-desktop-portal-kde-5.13.3
fosero/flatpak-overlay pull request #17
Opened 2018-07-17 23:43 UTC by seiflek

This provides the xdg-desktop-portal-kde that i wrote couple days ago, i've tested it for quite a bit, but still needs some more testing and some feedback.

2018-07-18 14:04 UTC, fosero requested changes
I don't mind adding this, but I am no KDE user at all. So I can't test.

It would need to be updated by you (or anyone willing) to keep it in the tree over time.

2018-07-18 14:04 UTC, fosero commented on sys-apps/xdg-desktop-portal-kde/xdg-desktop-portal-kde-5.13.3.ebuild
> +HOMEPAGE="https://www.kde.org/workspaces/plasmadesktop/"
I would prefer if this points to the actual git repo.

2018-07-18 14:04 UTC, fosero commented on sys-apps/xdg-desktop-portal-kde/xdg-desktop-portal-kde-5.13.3.ebuild
> +		)
I don't see wayland as optional in the cmake file?

Also, make this a single line:

```sh
wayland? ( >=kde-frameworks/kwayland-5.42.0 )
```

2018-07-18 14:04 UTC, fosero commented on sys-apps/xdg-desktop-portal-kde/xdg-desktop-portal-kde-5.13.3.ebuild
> +"
I seem to miss some deps mentioned in cmake file (eg. concurrent), but I am not up-to-date on qt/kde.

2018-07-18 15:52 UTC, seiflek commented
Making kde-frameworks/kwayland and dev-qt/qtconcurrent a strict deps for it seems fine, although i think the package should of existed with the kde stack in Gentoo upstream tree and packaged in a more proper manner using `inherit kde5` with the current deps in order to integrate tightly with the rest of the stack.

`DEPEND="`
`    $(add_frameworks_dep extra-cmake-modules)`
`    $(add_frameworks_dep ki18n)`
`    $(add_frameworks_dep knotifications)`
`    $(add_frameworks_dep kcoreaddons)`
`    $(add_frameworks_dep kwidgetsaddons)`
`    $(add_frameworks_dep kwayland)`
`    $(add_qt_dep qtcore)`
`    $(add_qt_dep qtgui)`
`    $(add_qt_dep qtwidgets)`
`    $(add_qt_dep qtconcurrent)`
`    $(add_qt_dep qtdbus)`
`    $(add_qt_dep qtprintsupport)`
`"`

I did package it for the sake of filling the gap, cause i saw a lot of people requesting it. And for upgrading and testing it, i'll take on it until the kde-team in Gentoo decide to implement it upstream, which i think will be the case soon since it's officially part of the kde familly.

2018-07-19 09:51 UTC, seiflek commented
I also think sys-app/ is not the right place for it, it should exist in kde-plasma/

2018-07-19 14:33 UTC, closed without merging

2018-07-19 22:32 UTC, fosero commented
Did you mean to close this PR?

2018-07-20 00:18 UTC, seiflek commented
i re-wrote the ebuild to use `inherit kde5` to better integrate with KF version provided in Gentoo upstream tree. i'll re-submit it in another pull request.